CodeFirst/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CodeFirst.Models;
using Microsoft.AspNet.Identity;


namespace CodeFirst.Controllers
{
    public class UserProfileController : Controller
    {
        // GET: UserProfile
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Save(HttpPostedFileBase Uploadlogo, M_Profile model)
        {
            if (ModelState.IsValid)
            {
                if (Uploadlogo != null && Uploadlogo.ContentLength > 0)
                {
                    string fileName = System.IO.Path.GetFileNameWithoutExtension(Uploadlogo.FileName);
                    string ext = System.IO.Path.GetExtension(Uploadlogo.FileName);
                    try
                    {
                        string logofile = fileName + "_" + User.Identity.GetUserId() + ext;
                        var path = System.IO.Path.Combine(Server.MapPath("~/Logo"), logofile);
                        Uploadlogo.SaveAs(path);
                        model.CompanyLogo = path;
                        try
                        {
                            model.SaveProfile();
                        }
                        catch (CustomSqlException ex)
                        {
                            ex.LogException();
                            return RedirectToAction("Index");
                        }

                    }
                    catch (Exception)
                    {

                        throw;
                    }
                }
            }
            return View("Index");
        }

    }
}

CodeFirst/Views/UserProfile/Index.cshtml
@model CodeFirst.Models.M_Profile

<div id="page-wrapper">
    <div class="h3">Profile page</div><hr />
    <div class="row">
        @using (Html.BeginForm("Save", "UserProfile", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="col-md-2">
                <div class="form-group">
                    <label>Organization Name</label><br />
                </div>
                <div class="form-group">
                    <label>Domain Used</label><br />
                </div>
                <div class="form-group">
                    <label>Organization Logo</label><br /><br />
                </div>
                <button type="submit" class="btn btn-primary" style="float:right">Save</button>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.TextBoxFor(model => model.CompanyName, htmlAttributes: new { @class = "form-control", @required = "required", @style = "Width:400px" })
                </div>
                <div class="form-group">

                    @Html.TextBoxFor(model => model.Domain, htmlAttributes: new { @class = "form-control", @required = "required", @style = "Width:400px" })
                </div>
                <div class="form-group">
                    <input type="file" name="Uploadlogo" required>
                </div>
                <button type="button" class="btn btn-primary">Cancel</button>
            </div>
        }
    </div>
</div>