CodeFirst/Backup/Controllers/SubscriberController.cs
using CodeFirst.Models;
using CodeFirst.ViewModels;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Excel;
using LumenWorks.Framework.IO.Csv;
using System.Data;
using System.IO;

namespace CodeFirst.Controllers
{
    public class SubscriberController : Controller
    {
        string userID = null;
        NewList list = null;
        Subscriber subscriber = null;
        public string GetUser()
        {
            userID = User.Identity.GetUserId();
            return userID;
        }
        // GET: Subscriber
        [HttpGet]
        public ActionResult AddSubcriber(int? id)
        {
            userID = GetUser();
            list = new NewList();
            subscriber = new Subscriber();
            if (id == null)
            {
                // ViewBag.ListName = new SelectList(dbcontext.NewLists, "ListID", "ListName", "Select List");
                ViewBag.ListName = new SelectList(NewList.GetLists(), "ListID", "ListName", "Select List");
            }
            else {
                subscriber.ListID = id;
                return View(subscriber);
            }
            return View(subscriber);
        }
        [HttpPost]
        public ActionResult AddSubcriber(Subscriber model)
        {
            userID = GetUser();
            if (model != null)
            {
                try
                {
                    model.saveSubscriber(userID);
                }
                catch (CustomSqlException ex)
                {
                    ModelState.AddModelError("addsub", ex.message);
                    return RedirectToAction("AddSubcriber/" + model.ListID);
                }
                
            }
            return RedirectToAction("Index", "List");
        }

        [HttpGet]
        public ActionResult ViewSubscribers(int? id, int? page)
        {
            userID = GetUser();
            const int pageSize = 30;
            int pageNumber = (page ?? 1);
            subscriber = new Subscriber();
            List<Subscriber> subscribersToList = new List<Subscriber>();
            if (id != null)
            {
                ViewBag.ListID = id;
                try
                {
                    subscribersToList = subscriber.GetSubscribersbyListID(id);
                    return View(subscribersToList.ToPagedList(pageNumber, pageSize));
                }
                catch (CustomSqlException ex)
                {
                    ModelState.AddModelError("viewsub", ex.message);
                    return RedirectToAction("index", "List");
                }
               
            }
            else {
                try
                {
                    subscribersToList = subscriber.GetAllSubscribers(userID);
                    return View(subscribersToList.ToPagedList(pageNumber, pageSize));
                }
                catch (CustomSqlException ex)
                {
                    ModelState.AddModelError("viewsub", ex.message);
                    return RedirectToAction("index", "Home");
                };
            }
        }
        [HttpGet]
        public ActionResult ImportSubcriber(int? id)
        {
            SubscribersViewModel model = new SubscribersViewModel();
            if (id == null)
            {
                ViewBag.ListName = new SelectList(NewList.GetLists(), "ListID", "ListName", "Select List");
            }
            else {
                model.ListID = id;
                return View(model);
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult ImportSubcriber(HttpPostedFileBase UploadFile, SubscribersViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (UploadFile != null && UploadFile.ContentLength > 0)
                {
                    if (UploadFile.FileName.EndsWith(".xlsx"))
                    {
                        try
                        {
                            subscriber.ImportExcel(UploadFile, model);
                        }
                        catch (CustomSqlException ex)
                        {
                            ModelState.AddModelError("importsub", ex.message);
                            return RedirectToAction("ImportSubcriber/" + model.ListID);
                        }
                       
                    }
                    else if (UploadFile.FileName.EndsWith(".xls"))
                    {
                        try
                        {
                            subscriber.ImportExcel(UploadFile, model);
                        }
                        catch (CustomSqlException ex)
                        {
                            ModelState.AddModelError("importsub", ex.message);
                            return RedirectToAction("ImportSubcriber/" + model.ListID);
                        }

                    }
                    else if (UploadFile.FileName.EndsWith(".csv"))
                    {
                        try
                        {
                            subscriber.ImportCSV(UploadFile, model);
                        }
                        catch (CustomSqlException ex)
                        {
                            ModelState.AddModelError("importsub", ex.message);
                            return RedirectToAction("ImportSubcriber/" + model.ListID);
                        }
                    }
                }
            }
            return RedirectToAction("ViewSubscribers", model.ListID);
        }

        [HttpGet]
        public ActionResult EditSusbscriber(int? id)
        {
            if (id != null)
            {
                Subscriber model = new Subscriber();
                try
                {
                    model = model.Edit(id);
                    return View(model);
                }
                catch (CustomSqlException ex)
                {
                    ModelState.AddModelError("editsub", ex.message);
                    return RedirectToAction("EditSusbscriber/" + id);
                }
            }
            else {
                ModelState.AddModelError("idnull", "Error while processing request contact administrator");
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public ActionResult EditSusbscriber(Subscriber model)
        {
            if (model != null)
            {
                try
                {
                    model.Update();
                    return RedirectToAction("ViewSubscribers/" + model.ListID);
                }
                catch (CustomSqlException ex)
                {
                    ModelState.AddModelError("editsub", ex.message);
                    return RedirectToAction("EditSusbscriber/"+model.SubscriberID);
                }
            }
            else {
                ModelState.AddModelError("modelnull", "Error while processing request contact administrator");
                return RedirectToAction("Index");
            }
        }
        public ActionResult DeleteSusbscriber(int? id)
        {
            Subscriber model = new Subscriber();
            if (id != null)
            {
                try
                {
                    model.Delete(id);
                    return RedirectToAction("Index", "List");
                }
                catch (CustomSqlException ex)
                {
                    ModelState.AddModelError("editsub", ex.message);
                    return RedirectToAction("ViewSubscribers/" + ViewBag.id);
                }
            }
            else {
                ModelState.AddModelError("idnull", "Error while processing request contact administrator");
                return RedirectToAction("Index", "List");
            }
        }

        public ActionResult Unsubscribers(int? id)
        {
            userID = GetUser();
            subscriber = new Subscriber();
            SubscribersViewModel model = new SubscribersViewModel();
            try
            {
                model.SubscribersToList = subscriber.Unsubscriber(id);
                return View(model);
            }
            catch (CustomSqlException ex)
            {
                ModelState.AddModelError("unsub", ex.message);
                return RedirectToAction("Index","List");
            }
        }
    }
}

CodeFirst/Backup/Views/Subscriber/AddSubcriber.cshtml
@model CodeFirst.Models.Subscriber

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10">
            <h1 class="page-header">Add a subscriber</h1>
        </div>
        <div class="col-lg-2">
            @Html.ActionLink("List", "Index", "List", new { @class = "btn btn-sm btn-primary" })
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">        </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            @using (Html.BeginForm("AddSubcriber","Subscriber", FormMethod.Post))
                            {
                                @*@Html.HiddenFor(Model.ListID)*@
                                @Html.HiddenFor(model => model.ListID)
                                @Html.ValidationMessage("emailerror", new { @class = "text-danger" })
                                @Html.ValidationMessage("TransactionFailed", new { @class = "text-danger" })
                                @*<form role="form">*@
                            if (ViewBag.ListName != null)
                            {
                                <div class="form-group" style="width:200px">
                                    <label>Select List</label>
                                    @Html.DropDownListFor(model => model.ListID, (SelectList)ViewBag.ListName, "Select List", new { @class = "form-control", @id = "ddladdSub" })
                                </div>
                            }
                            <div class="form-group">
                                <label>First Name</label>
                                @*<input class="form-control" required>*@
                                @Html.TextBoxFor(model => model.FirstName, htmlAttributes: new { @class = "form-control", @required = "required" })
                            </div>
                            <div class="form-group">
                                <label>Last Name</label>
                                @*<input class="form-control" required>*@
                                @Html.TextBoxFor(model => model.LastName, htmlAttributes: new { @class = "form-control", @required = "required" })
                            </div>
                                <div class="form-group">
                                    <label>Email Address</label>
                                    @*<input class="form-control" required>*@
                                    @Html.TextBoxFor(model => model.EmailAddress, htmlAttributes: new { @class = "form-control", @required = "required" })
                                </div>
                                <button type="submit" class="btn btn-primary">Subscribe</button>
                                @*@Html.ActionLink("Subscribe", "AddSubcriber","List", new { @class = "btn btn-default" })*@
                                @*<button type="reset" class="btn btn-default">Cancel</button>*@
                                @Html.ActionLink("Cancel", "Index", "List", new { @class = "btn btn-default" })
                                @*</form>*@
                            }
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->
<!-- jQuery -->
<script src="~/Content/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="~/Content/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Metis Menu Plugin JavaScript -->
<script src="~/Content/bower_components/metisMenu/dist/metisMenu.min.js"></script>
<!-- Custom Theme JavaScript -->
<script src="~/Content/dist/js/sb-admin-2.js"></script>
<script type="text/javascript">
    $(function () {
        $("#ddladdSub").change(function () {
            debugger;
            $.ajax({
                url: '/AddSubcriber/'
            })
        })
    })
</script>

CodeFirst/Backup/Views/Subscriber/EditSusbscriber.cshtml
@model CodeFirst.Models.Subscriber

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10">
            <h1 class="page-header">Edit a subscriber</h1>
        </div>
        <div class="col-lg-2">
            @Html.ActionLink("List", "Index", "List", new { @class = "btn btn-sm btn-primary" })
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">        </div>
                @Html.ValidationMessage("idnull", new { @class = "text-danger" })
                @Html.ValidationMessage("modelnull", new { @class = "text-danger" })
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            @using (Html.BeginForm("EditSusbscriber", "List", FormMethod.Post))
                            {
                                @*@Html.HiddenFor(Model.ListID)*@
                                @Html.HiddenFor(model => model.ListID)
                                @Html.HiddenFor(model => model.SubscriberID)
                                @Html.ValidationMessage("emailerror", new { @class = "text-danger" })
                                @*<form role="form">*@
                            if (ViewBag.ListName != null)
                            {
                                <div class="form-group" style="width:200px">
                                    <label>Select List</label>
                                    @Html.DropDownListFor(model => model.ListID, (SelectList)ViewBag.ListName, "Select List", new { @class = "form-control", @id = "ddladdSub" })
                                </div>
                            }
                            <div class="form-group">
                                <label>First Name</label>
                                @*<input class="form-control" required>*@
                                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                <label>Last Name</label>
                                @*<input class="form-control" required>*@
                                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                <label>Email Address</label>
                                @*<input class="form-control" required>*@
                                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                                <button type="submit" class="btn btn-primary">Subscribe</button>
                                @*@Html.ActionLink("Subscribe", "AddSubcriber","List", new { @class = "btn btn-default" })*@
                                @*<button type="reset" class="btn btn-default">Cancel</button>*@
                                @Html.ActionLink("Cancel", "ViewSubscribers", "Subscriber", new { id = Model.ListID }, new { @class = "btn btn-default" })
                                @*</form>*@
                            }
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->
<!-- jQuery -->
<script src="~/Content/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="~/Content/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Metis Menu Plugin JavaScript -->
<script src="~/Content/bower_components/metisMenu/dist/metisMenu.min.js"></script>
<!-- Custom Theme JavaScript -->
<script src="~/Content/dist/js/sb-admin-2.js"></script>
<script type="text/javascript">
    $(function () {
        $("#ddladdSub").change(function () {
            debugger;
            $.ajax({
                url: '/AddSubcriber/'
            })
        })
    })
</script>

CodeFirst/Backup/Views/Subscriber/ImportSubcriber.cshtml
@using System.Data
@model CodeFirst.ViewModels.SubscribersViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10">
            <h1 class="page-header">Where do you want to import subscribers from?</h1>
        </div>
        <div class="col-lg-2">
            @Html.ActionLink("List", "Index", "List", new { @class = "btn btn-sm btn-primary" })
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">        </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            @Html.ValidationMessage("Fileerr", new { @class = "text-danger" })
                            @using (Html.BeginForm("ImportSubcriber", "Subscriber", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                @Html.HiddenFor(model => model.ListID)
                                @Html.ValidationMessage("FileError", new { @class = "text-danger" })
                                @Html.ValidationMessage("present", new { @class = "text-danger" })
                                @*<form role="form">*@
                            if (ViewBag.ListName != null)
                            {
                                <div class="form-group" style="width:200px">
                                    <label>Select List</label>
                                    @Html.DropDownListFor(model => model.ListID, (SelectList)ViewBag.ListName, "Select List", new { @class = "form-control" })
                                </div>
                            }
                            <div class="form-group">
                                <label>Select Import Format</label>
                                <div class="radio">
                                    <label>
                                        <input name="optionsRadios" id="optionsRadios1" value="option1" required type="radio">CSV or tab-delimited text file
                                    </label>
                                    @*@Html.ActionLink("Sample CSV File", "SampleCSV", "List", new { @filename = "SampleCSV" }, new { @target = "_blank" })*@
                                </div>
                                <div class="radio">
                                    <label>
                                        <input name="optionsRadios" id="optionsRadios2" value="option2" type="radio">Excel Import
                                    </label>

                                </div>
                                @Html.ActionLink("Sample Excel File", "SampleExcel", "List", new { @filename = "SampleExcel" }, new { @target = "_blank" })
                                <hr />
                                <div class="form-group">
                                    <label>File input</label>
                                    <input type="file" name="UploadFile" required>
                                </div>
                                <hr>
                            </div>
                            <button type="submit" class="btn btn-primary">Import</button>
                                @*<button type="reset" class="btn btn-default">Cancel</button>*@
                                @Html.ActionLink("Cancel", "Index", "List", null,new { @class = "btn btn-default" })
                                @*</form>*@
                            if (Model != null)
                            {
                                if (Model.dataTable != null)
                                {
                                    <h3 class="text-primary">List Imported successfully</h3>
                                    <div class="dataTable_wrapper">
                                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                            <thead>
                                                <tr>
                                                    @foreach (DataColumn col in Model.dataTable.Columns)
                                                    {
                                                        <th>@col.ColumnName</th>
                                                    }
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (DataRow row in Model.dataTable.Rows)
                                                {
                                                    <tr>
                                                        @foreach (DataColumn col in Model.dataTable.Columns)
                                                        {
                                                            <td>
                                                                @row[col.ColumnName]
                                                            </td>
                                                        }
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                    }
                                }
                            }
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>

<!-- /#page-wrapper -->
<!-- jQuery -->
<script src="~/Content/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="~/Content/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Metis Menu Plugin JavaScript -->
<script src="~/Content/bower_components/metisMenu/dist/metisMenu.min.js"></script>
<!-- Custom Theme JavaScript -->
<script src="~/Content/dist/js/sb-admin-2.js"></script>

CodeFirst/Backup/Views/Subscriber/Unsubscribers.cshtml
@model CodeFirst.ViewModels.SubscribersViewModel

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10">
            <h1 class="page-header">View UnSubscriber</h1>
        </div>
        <div class="col-lg-2">
            @Html.ActionLink("List", "Index", "List", new { @class = "btn btn-sm btn-primary" })
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Subscribers to list
                </div>

                <!-- /.panel-heading -->
                <div class="panel-body">
                    @if (Model.SubscribersToList.Count != 0)
                    {
                        @Html.ValidationMessage("present", new { @class = "text-danger" })
                        <div class="dataTable_wrapper">
                            <table class="table  table-hover">

                                <thead>
                                    <tr>
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Email</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model.SubscribersToList)
                                    {
                                        <tr class="odd gradeX">
                                            <td>
                                                @Html.DisplayFor(modelitem => item.FirstName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelitem => item.LastName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelitem => item.EmailAddress)
                                            </td>

                                        </tr>
                                    }

                                </tbody>
                            </table>

                            @*<nav>
                                <ul class="pager">
                                    <li><a href="#">Previous</a></li>
                                    <li><a href="#">Next</a></li>
                                </ul>
                            </nav>*@
                        </div>
                    }


                    else {

                        <p>No Unsubscribers in list</p><br />
                    }
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    @Html.ActionLink("Back", "Index", "List",null, new { @class = "btn btn-primary" })
</div>
<!-- /#page-wrapper -->